language: node_js
node_js:
  - "10"
services:
  - docker
cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - npm run build
  - echo 'build success'

after_script:
  - docker build -t asd285653184/koa .
  - docker push asd285653184/koa
  